// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHntPLa0l4dS40cqjLS0vqsGe6JHlWFr0',
    appId: '1:334113013168:web:a7381d9bbd71f6b370ea75',
    messagingSenderId: '334113013168',
    projectId: 'netflix-clone-64778',
    authDomain: 'netflix-clone-64778.firebaseapp.com',
    databaseURL: 'https://netflix-clone-64778-default-rtdb.firebaseio.com',
    storageBucket: 'netflix-clone-64778.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBudm13JQsXifv1ruOBbFPdv_aib_OxSps',
    appId: '1:334113013168:android:fc364a090b93e3d070ea75',
    messagingSenderId: '334113013168',
    projectId: 'netflix-clone-64778',
    databaseURL: 'https://netflix-clone-64778-default-rtdb.firebaseio.com',
    storageBucket: 'netflix-clone-64778.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDqM3NsXnmwY-w0FWW9b3n_tDF-1ZI6i4Q',
    appId: '1:334113013168:ios:8b174565326b510c70ea75',
    messagingSenderId: '334113013168',
    projectId: 'netflix-clone-64778',
    databaseURL: 'https://netflix-clone-64778-default-rtdb.firebaseio.com',
    storageBucket: 'netflix-clone-64778.appspot.com',
    iosClientId: '334113013168-mvto5tev5mh1bgc526dmah7b847552fm.apps.googleusercontent.com',
    iosBundleId: 'com.example.netflixCloneApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDqM3NsXnmwY-w0FWW9b3n_tDF-1ZI6i4Q',
    appId: '1:334113013168:ios:1110b9e11d4fd0e270ea75',
    messagingSenderId: '334113013168',
    projectId: 'netflix-clone-64778',
    databaseURL: 'https://netflix-clone-64778-default-rtdb.firebaseio.com',
    storageBucket: 'netflix-clone-64778.appspot.com',
    iosClientId: '334113013168-p9jg0rdtjr5qc7c1ior3l4u1o93cbm9k.apps.googleusercontent.com',
    iosBundleId: 'com.example.netflixCloneApp.RunnerTests',
  );
}
